### PR TITLE
This branch adds support for nested helm dependencies

### PR DESCRIPTION
**Pull request by shortwavedave**
The previous implementation had a recursive function but it terminated after one level 
This branch adds support for nested repository urls - the previous implementation only supported a single level

Resolves: #67

### CODE REVIEW

**Review by mpermar — COMMENTED** [review]
Looks good. Very nice catch.

**Comment by mpermar** [comment]
Actually @shortwavedave I've been testing the relocation with your branch and it indeeds solves the problems with nested Helm charts, but it seems it causes some regressions. This PR was going to need a rebase anyways. Are you interested in driving this one forward?

**Comment by shortwavedave** [comment]
@mpermar thanks for reviewing - I thought I had run the tests in the repository. I can drive forward - could you share what regressions you see please?

**Comment by shortwavedave** [comment]
oh I see the checks that have failed in this PR - ok I'll take a look

**Comment by mpermar** [comment]
@shortwavedave closing in favor of #83. Really appreciated the heads up and contribution.

**Pull request closed without merging**
